### DISCUSSION TITLE
failed to initialize database

### DISCUSSION THREAD

**Discussion by Snofroy** [terralist/terralist#312] [Q&A] [answered]
Hi, I got an error when running your application on Linux:

```
~ ./terralist server --config config.yaml                                                                                                                                                                                                                              sudo-3 | 0 [15:27:06]
{"level":"error","time":"2024-08-15T15:27:08+03:00","message":"failed to initialize database, got error Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub"}
{"level":"error","error":"Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub","time":"2024-08-15T15:27:08+03:00"}
```

**Comment by Snofroy** [comment]
````
~ sudo docker run --rm -it -p 5758:5758 -v ~/tmp/terralist:/app ghcr.io/terralist/terralist server --config /app/config.yaml                                                   1 [12:12:29]
{"level":"error","time":"2024-08-16T09:13:12Z","message":"failed to initialize database, got error unable to open database file: no such file or directory"}
{"level":"error","error":"unable to open database file: no such file or directory","time":"2024-08-16T09:13:12Z"}
````

**Comment by valentindeaconu** [comment, marked as answer]
Hello! Not sure what is wrong with your configuration, but I tried the Docker image and it works:

```
$ docker run --rm -it -p 5758:5758 -v $PWD:/app ghcr.io/terralist/terralist server --config /app/config.yaml
{"level":"warn","time":"2024-08-23T11:20:37Z","message":"Terralist is running in HTTP mode which is not supported by Terraform. If you're using a proxy to serve on HTTPS, ignore this warning."}
{"level":"info","time":"2024-08-23T11:20:37Z","message":"Terralist started, listening on port 5758"}
```

This is my configuration file:

```yaml
port: 5758
log-level: debug
oauth-provider: github
gh-client-id: test
gh-client-secret: test
token-signing-secret: "somerandomvalue"
database-backend: "sqlite"
sqlite-path: "/app/example.db"
modules-storage-resolver: "proxy"
providers-storage-resolver: "proxy"
session-store: "cookie"
cookie-secret: "someotherrandomvalue"
```

Regarding the CGO issue, I think I know the issue, when I started this project I was using a different sqlite driver which required `CGO_ENABLED=0`. Now, we can get rid of that, since it is only used for the binary releases.

https://github.com/terralist/terralist/blob/3551537ce82ad5e284afea15ab74dc98be1f549f/.goreleaser.yml#L2
