### DISCUSSION TITLE
Please help me understand how local file uploads work

### DISCUSSION THREAD

**Discussion by garrettprimm** [terralist/terralist#456] [Q&A] [answered]
Good evening,

I'm evaluating terralist as a private module registry. I think its an awesome idea and I'm really glad you guys are doing this. There is a need for this in the terraform world. 

I'm attempting get file upload for a module working.

I'm using this command for upload
```bash
curl -vv -L -X POST \                                                                                               
   -H "Authorization: Bearer x-api-key:$MY_API_TOKEN" \
  -F "module=@test-module.zip"\
  http://localhost:5758/v1/api/modules/test-module/asdad/1.2.0/upload-files
```

I'm getting the following error
{"errors":["could store the new version: not yet implemented"]}

Can you help me understand what ":provider" is for in this url path and how should I structure the url for creating modules with storage on the server itself?

POST /v1/api/modules/:name/:provider/:version/upload-files

Here's the content of my config file
```yaml
providers-anonymous-read: true
custom-company-name: Example-Company
oauth-provider: "github"
gh-client-id: ----REDACTED----
gh-client-secret: ----REDACTED----
token-signing-secret: "supersecretstring"
cookie-secret: secret
s3-server-side-encryption: none
sqlite-path: /app/sqlite
modules-storage-resolver: local
```
