### ISSUE TITLE
NPM in the dependabot

### ISSUE THREAD

**Issue by DariuszPorowski** [terralist/terralist#260]
Hi @valentindeaconu Great project, thanks for it!

Consider adding the `npm` to `.github/dependabot.yml` to keep node deps up to date.

```yaml
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
```
